server:
  port: 7001
spring:
  application:
    name: eureka-service2

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7000/eureka/  #注册到eureka-service1
  instance:
      hostname: service2